services:
  sempl-it-backend:
    container_name: 'sempl-it-backend'
    image: 'sempl-it-backend'
    build: '.'
    restart: 'unless-stopped'
    ports:
      - '8000:8000'
    environment:
      - 'PYTHONUNBUFFERED=1'
      - 'USE_ONNX_RUNTIME=${USE_ONNX_RUNTIME:-False}'
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:8000/api/v1/healthcheck' ]
