services:
  sempl-it-backend:
    container_name: 'sempl-it-backend'
    image: 'sempl-it-backend'
    build: '.'
    restart: 'unless-stopped'
    ports:
      - '8000:8000'
    healthcheck:
      test: [ 'CMD', 'curl', '--fail', 'http://localhost:8000/api/v1/healthcheck' ]
